### ISSUE TITLE
Test failures on FreeBSD 11.1

### ISSUE THREAD

**Issue by krader1961** [att/ast#577]
We have reduced the consistent unit test failure count on macOS, various Linux distros, and OpenBSD to zero. One platform, FreeBSD 11.1, still has 17 unit tests failing on a consistent basis. Three of those are in the `wchar` test. Here is a sample failure log from that unit test:

```
--- stdout ---
<I> wchar[-1]: TEST_DIR=/tmp/ksh.wchar.XXXXXXX.UlUVLNOF
<I> wchar[33]: LC_ALL=en_US.UTF-8 is supported and will be tested
<I> wchar[35]: LC_ALL=en_US.utf8 not supported
<I> wchar[35]: LC_ALL=en_US.ISO-8859-15 not supported
<I> wchar[35]: LC_ALL=en_US.iso885915 not supported
<I> wchar[33]: LC_ALL=zh_CN.GB18030 is supported and will be tested
<I> wchar[35]: LC_ALL=zh_CN.gb18030 not supported
--- stderr ---
<E> wchar[49]: C.UTF-8 nounicodeliterals FAILED
<E> expect: |0000000 24 27 e2 82 ac 27 0a|
<E> actual: |0000000 24 27 5c 75 5b 32 30 61 63 5d 27 0a|
<E> wchar[55]: C.UTF-8 (nounicodeliterals) FAILED
<E> expect: |0000000 24 27 e2 82 ac 27 0a|
<E> actual: |0000000 24 27 5c 75 5b 32 30 61 63 5d 27 0a|
<E> wchar[49]: zh_CN.GB18030 nounicodeliterals FAILED
<E> expect: |0000000 24 27 e2 82 ac 27 0a|
<E> actual: |0000000 27 5c 75 5b 32 30 61 63 5d 27 0a|
<E> wchar[55]: zh_CN.GB18030 (nounicodeliterals) FAILED
<E> expect: |0000000 24 27 e2 82 ac 27 0a|
<E> actual: |0000000 27 5c 75 5b 32 30 61 63 5d 27 0a|
<W> wchar[-1]: error_count = 4
-------
```

And from the `builtins` unit test:

```
<E> builtins[393]: printf "%T" now = Mon Jun  4 22:00:23 PPT 2018 != Mon Jun  4 22:00:23 PDT 2018
```

Notice the change in TZ .  from `PPT` to `PDT`.

**Comment by krader1961** [comment]
The `wchar` test failures are due to the `C.UTF-8` locale. On all the systems I've been testing on other than FreeBSD this behavior is seen:

```
$ printf "%q\n" "$(printf "\u[20ac]")"
$'€'
$ export LC_ALL=C.UTF-8
$ printf "%q\n" "$(printf "\u[20ac]")"
$'€'
```

On FreeBSD 11.1 this behavior is seen:

```
$ printf "%q\n" "$(printf "\u[20ac]")"
$'€'
$ export LC_ALL=C.UTF-8
$ printf "%q\n" "$(printf "\u[20ac]")"
$'\u[20ac]'
```

Note that the initial locale is en_US.UTF-8. This doesn't surprise me very much because as I've mentioned before (in a different issue where this weird locale as discussed) the `C` locale by definition is supposed to be just plain ASCII. It doesn't even have to support ISO 8859 (i.e., code points between 128 and 255). See this [StackOverflow question](https://stackoverflow.com/questions/15649165/behavior-of-extended-bytes-characters-in-c-posix-locale).

**Comment by krader1961** [comment]
LOL and crying (again). The reason the `wchar` unit test is failing on FreeBSD is because of this block in *src/cmd/ksh93/sh/string.c*:

```
#if !_lib_iswprint && !defined(iswprint)
#define iswprint(c) (((c) & ~0377) || isprint(c))
#endif
```

Because we currently do not have a feature test for `iswprint()` and there is no other macro of that name we end up with that incorrect, brain-dead, implementation on most platforms. However, on FreeBSD the *wchar.h* header defines `iswprint` as a macro. Thus we end up using the system implementation on FreeBSD. Which, for whatever reason, doesn't think the Euro symbol is printable.

**Comment by krader1961** [comment]
> Which, for whatever reason, doesn't think the Euro symbol is printable.

I just realized why it doesn't think the Euro symbol is printable. It's because the locale is `C.UTF-8` which is an AST invention not recognized by any other locale subsystem. And in the `C` language locale wide chars are by definition not printable. I'm off to make a stiff drink while I ponder why the people who wrote this code thought this sort of thing was a good idea.

**Comment by siteshwar** [comment]
> I just realized why it doesn't think the Euro symbol is printable. It's because the locale is C.UTF-8 which is an AST invention not recognized by any other locale subsystem.

`C.UTF-8` is recognized on Fedora, although the patch is not in upstream yet. You can see it [here](https://src.fedoraproject.org/cgit/rpms/glibc.git/tree/glibc-c-utf8-locale.patch).

**Comment by krader1961** [comment]
The `wchar` unit test, as noted above, is still failing on FreeBSD 11.1 for the zh_CN.GB18030 locale. I spent a few hours today delving into the code and adding diagnostic prints. The failure is the call of the system `iconv()` that occurs indirectly via this statement in *src/lib/libast/comp/iconv.c*:

```
if ((*cc->from.fun)(cc->cvt, fb, fn, tb, tn) == (size_t)(-1)) {
```

So the next question is whether that is due to a bug in the AST code or a problem with the system provided `iconv()` function. To test this I wrote a trivial program, completely outside this project, that does the same conversion of the Euro currency symbol. Lo and behold. That program succeeds on all my platforms except FreeBSD 11.1. If I change the destination encoding to something like ISO8859-15 it succeeds on all my platforms. The conclusion is that FreeBSD 11.1 does not know how to convert the Unicode Euro currency symbol in UTF-8 encoding, U+20AC, to GB18030 encoding.

**Comment by krader1961** [comment]
I've fixed all the test failures on FreeBSD 11.1.

**Comment by siteshwar** [comment]
I am still getting this error for `directoryfd` test under FreeBSD:

```
<E> directoryfd[119]: test_dirfd_basics1/createfile1_redirect/redirect {dirfd}<"./tmp" ; print "foo1" >/proc/$$/fd/${dirfd}//test1 ; cat tmp/test1 ; true: Expected stdout to match
<E> expect: |foo1|
<E> actual: ||
<E> directoryfd[123]: test_dirfd_basics1/createfile1_redirect/redirect {dirfd}<"./tmp" ; print "foo1" >/proc/$$/fd/${dirfd}//test1 ; cat tmp/test1 ; true: Expected empty stderr
<E> expect: ||
<E> actual: |/usr/home/situ/upstream/ast/build/src/cmd/ksh93/ksh: /proc/65712/fd/11//test1: cannot create [No such file or directory]|
/tmp/ksh.directoryfd.XXXXXXX.BFiEzyNw/directoryfd.sh[211]: test_dirfd_basics1: line 202: (
        typeset -l -i res=1
        stderr='/usr/home/situ/upstream/ast/build/src/cmd/ksh93/ksh: /proc/65712/fd/11//test1: cannot create [No such file or directory]'
        stdout=''
).res: arithmetic syntax error
<W> directoryfd[-1]: error_count = 2
```
